### ISSUE TITLE
Could not mount drive (Kingston 4GB HC SD).

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/SummerCart64#30]
**Describe the bug**
Using this SD card results in `A hard error occured in the low level disk I/O layer`.

**To Reproduce**
Steps to reproduce the behaviour:
1. 
2. 
3. 
4. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11439699/220184151-f588906c-e247-4acb-8f01-332e301f4921.png)

![image](https://user-images.githubusercontent.com/11439699/220184231-58dace84-f000-420a-9c77-c0e89e5a6532.png)

**Expected behavior**

**Possible solution**
Not obligatory, but suggest a fix/reason for the bug.

**Comment by Polprzewodnikowy** [comment]
Could you test SD card again with this firmware and post screenshots here? [sc64_update_package.zip](https://github.com/Polprzewodnikowy/SummerCart64/files/10787345/sc64_update_package.zip)

**Comment by networkfusion** [comment]
![image](https://user-images.githubusercontent.com/11439699/220189005-bf504737-1546-467a-992b-a9c29e196738.png)


FYI, I found a Samsung Pro Endurance 128 SD card and that one works, so I know that at least it is not a H/W issue.

**Comment by Polprzewodnikowy** [comment]
Ok, that helps a lot. Your card doesn't support CMD23. I need to rewrite code to remove it.

**Comment by Polprzewodnikowy** [comment]
This firmware has removed usage of CMD23. [sc64_update_package_no_cmd23.zip](https://github.com/Polprzewodnikowy/SummerCart64/files/10787997/sc64_update_package_no_cmd23.zip) Can I ask you for one more test?

**Comment by networkfusion** [comment]
![image](https://user-images.githubusercontent.com/11439699/220208166-cf304f12-4660-4709-ba11-be50d0040257.png)

All good 👍

**Comment by networkfusion** [comment]
![image](https://user-images.githubusercontent.com/11439699/220208384-51abc937-24f9-41cb-b9bc-5e615f351d76.png)

**Comment by Polprzewodnikowy** [comment]
Fixed in https://github.com/Polprzewodnikowy/SummerCart64/commit/98fa69e4d71977daf2ca423bad60acde1c58c361
