### ISSUE TITLE
Rewrite sc64.py in compiled language to avoid detecting it as malicious software on Windows OS

### ISSUE THREAD

**Issue by Polprzewodnikowy** [Polprzewodnikowy/SummerCart64#34]
**Describe the bug**
As it turns out, using `pyinstaller` or `Nuitka` to generate executables results in terrible experience both on Windows and macOS. On Windows application is detected either as Trojan or Virus. On macOS performance and ease of use is hindered because of system protective measures.

**To Reproduce**
1. Run `sc64.exe` on Windows OS
2. Executable is detected as malicious software

**Expected behavior**
`sc64` executable shouldn't be detected as malicious software

**Possible solution**
Rewrite application in compiled language like C, Rust or Go.

**Comment by networkfusion** [comment]
Or .Net 😉

**Comment by Polprzewodnikowy** [comment]
Fixed in https://github.com/Polprzewodnikowy/SummerCart64/commit/1e19b648fb6b5bcecfe99b6c17d7c3c987945f0a
