### ISSUE TITLE
Add ability to upload file to SD over USB

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/SummerCart64#42]
When developing the N64FlashcartMenu, it is advantagous to be able to "save" or "overwrite" certain ROM's to the SD card without having to remove the SD card.

examples:

* replace the current `sc64menu.n64` at certain save points.
* Add a new ROM for testing.
* overwrite the `config.ini`

Currently it requires that I remove the SD card to manage its content.

I propose that theUSB loader functionality is able to support it.

**Comment by Polprzewodnikowy** [comment]
sc64deployer already can upload files via USB but app running on the N64 needs to listen to the commands. No direct SD card access via USB was a deliberate choice as it would add too much complexity for my liking. One improvement I might add to the PC app is ability to close itself after reaching EOF from stdio. It would be much easier to add batch commands and pipe stdio as debug command, something like `echo '@output/sc64menu.n64@ | sc64deployer debug`

**Comment by Polprzewodnikowy** [comment]
I thought about this issue and there's a better way to achieve this. To do this, it is necessary to use something like [FUSE](https://github.com/libfuse/libfuse) or [WinFSP](https://github.com/winfsp/winfsp) and have daemon software running on the N64. For instance N64FlashcartMenu can have option to put it in special file transfer mode while another piece of software running on the PC would communicate via UNFLoader protocol and expose SD card inserted into flashcart as just regular drive. This is much more user friendly as opposed to using terminal tools. As a bonus this would enable file transfer not only on the SC64, but also any other flashcart capable of running N64FlashcartMenu.

Closing this issue as this needs to be implemented elsewhere.
