### ISSUE TITLE
Add N64FlashcartMenu to readme

### ISSUE THREAD

**Issue by networkfusion** [Polprzewodnikowy/SummerCart64#51]
**Is your feature request related to a problem? Please describe.**
The current readme flashcart features does not take into account the N64FlashcartMenu.

**Describe the solution you'd like**
Add a link to the repo.

**Additional context**
It should be obvious, but most people will not connect the dots. Most "users" will not read between the lines about how great both parts are when combined.

**Comment by Polprzewodnikowy** [comment]
Fixed in https://github.com/Polprzewodnikowy/SummerCart64/pull/56
