### ISSUE TITLE
Programming bootloader failed

### ISSUE THREAD

**Issue by xgsh159** [Polprzewodnikowy/SummerCart64#59]
<img width="423" alt="01" src="https://github.com/Polprzewodnikowy/SummerCart64/assets/10721037/73af899c-290e-44bc-9f12-4ac46d475840">

_Originally posted by @xgsh159 in https://github.com/Polprzewodnikowy/SummerCart64/discussions/58_

**Comment by Polprzewodnikowy** [comment]
Not an issue with the project, let's keep discussion in one place
