### ISSUE TITLE
Freezing Issues / Muffled Amplified Sound

### ISSUE THREAD

**Issue by Kinooshi823** [Polprzewodnikowy/SummerCart64#70]
**Describe the bug**

I tested Killer Instinct Gold, Mortal Kombat Trilogy, and F-Zero Expansion Pak for the 64DD and experienced issues from amplified muffling sound fx. And freezing during gameplay. When this issue occurs, pressing reset on the console does not boot up to the screen. The cart must be ejected and reinserted to enter the menu once more. 

**To Reproduce**
1. Play Killer Instinct Gold and after several fights, the issue begins with sounds being loud and muffled and then the game will freeze.
2. Mortal Kombat Trilogy experiences the same loud and muffled noise while in the main menu and then it freezes.
3. F-Zero expansion pak will experience loud and muffled noise while playing DD stage 1. After the race is completed, the game will either freeze or receive an error 41 code. The screen will turn black. Pressing reset on the console does not show anything. The cart must be removed and reinserted. 
4. 

**Screenshots**

**Expected behavior**

I expected gameplay to work perfectly fine or at least close to it. So far all of the games I have played, I have been unable to finish them. 

**Possible solution**
Not obligatory, but suggest a fix/reason for the bug.

A fix via software update. I cannot connect cart to USB as it is not detected as I am unsure how to update the firmware or reapply firmware.

**Comment by Polprzewodnikowy** [comment]
Sorry but this sounds like a faulty hardware and no firmware update would help here. Can you post photos of the PCB with marking on the chips visible? While I might believe your cart uses required parts, there's still a possibility a different part was used that is not compatible.
Also please run built-in tests by holding button on the back of the SC64 while switching power on the console. Let tests run in a loop for some time and report results here.

**Comment by Pheeeeenom** [comment]
> Sorry but this sounds like a faulty hardware and no firmware update would help here. Can you post photos of the PCB with marking on the chips visible? While I might believe your cart uses required parts, there's still a possibility a different part was used that is not compatible. Also please run built-in tests by holding button on the back of the SC64 while switching power on the console. Let tests run in a loop for some time and report results here.

@Polprzewodnikowy This is one of my carts, the BOM is the "fixed" PCBWay one.

**Comment by Kinooshi823** [comment]
I will run tests now. I would also like to add that I got this cart from Phenom Mod. I reached out to whoever runs the site and they said it was a software issue and pointed me here.

**Comment by Kinooshi823** [comment]
I ran the test twice and both times I got a "Mismatch" and it stops from there..


![cart1](https://github.com/Polprzewodnikowy/SummerCart64/assets/168611462/32b7da8d-5e25-49db-92a2-b662cf903718)



![IMG_5254](https://github.com/Polprzewodnikowy/SummerCart64/assets/168611462/6d910b88-0b73-48c5-bc42-4b8d86dd3399)

**Comment by Polprzewodnikowy** [comment]
Right, there's definitely something wrong with the connection between SC64 and your console. Before drawing any conclusions you can try:
- Clean your cartridge slot in the console with an alcohol
- Run the game with USB cable connected to a power source, doesn't matter if it's not recognized by the computer
- Replace your power supply
I hope you've tested your console with a retail game beforehand and it works without any hiccups. Keep in mind that custom cartridges draw more power and your power supply might just barely provide enough power to run retail game, while SC64 might get underpowered.

**Comment by Kinooshi823** [comment]
My nintendo 64 works fine with other carts. I have an ED64 and an Everdrive X7 and never had issues. I have retail games and never had issues. My power bricks are fine as I have 2 of them. The console was of course cleaned since I put on a new shell.

**Comment by Kinooshi823** [comment]
I will test this with my spare Nintendo 64 I have. I will post results.

**Comment by networkfusion** [comment]
It could also be N64 slot pins being slightly widened with regards to the PCB depth of the SC64 PCB, especially if the PCB was ordered in the wrong depth (1.2mm).

**Comment by Kinooshi823** [comment]
> It could also be N64 slot pins being slightly widened with regards to the PCB depth of the SC64 PCB, especially if the PCB was ordered in the wrong depth (1.2mm).

I purchased this from Phenom Mod.

**Comment by Pheeeeenom** [comment]
The pcb thickness is whatever the PCBWay share project is

**Comment by networkfusion** [comment]
![image](https://github.com/Polprzewodnikowy/SummerCart64/assets/11439699/0a37c1db-583c-42af-b937-6681a798ac39)

**Comment by Kinooshi823** [comment]
I have tested this with 2 N64's. 2 different power supplies and one attached with the actual DD. All 3 mismatch errors. This is the only Nintendo 64-related item in my possession that gives me issues. I think the cart is faulty. Getting another one would prove if I was right or wrong. 


![sc1](https://github.com/Polprzewodnikowy/SummerCart64/assets/168611462/80bd6929-e45f-419f-8eff-6dfc1da5467f)
![sc2](https://github.com/Polprzewodnikowy/SummerCart64/assets/168611462/013aa39d-d97a-4221-a2ed-b03ee3dd78fc)
![sc3](https://github.com/Polprzewodnikowy/SummerCart64/assets/168611462/63fbc720-7fb9-4c9f-97ed-86b77da0bddf)

**Comment by Kinooshi823** [comment]
> Yeah that definitely seems like a faulty unit. Thank you for the photos, I can see that bits 8, 9, 10 and 11 are wrong. I suspect faulty SDRAM chip but confirming that would require testing the memory via USB interface and I have not developed such test yet.

So then I would have to open an RMA at Phenom Mods? That is where I got the Summercart from.

**Comment by Pheeeeenom** [comment]
Yes. Email me your order number and I'll send you a replacement and a return label

**Comment by Kinooshi823** [comment]
> Yes. Email me your order number and I'll send you a replacement and a return label

Email sent

**Comment by networkfusion** [comment]
@Kinooshi823 Suggest you close this issue. Just to keep the repo issues clear.

**Comment by Pheeeeenom** [comment]
I got the cart back. Some bad news is that the hardware is fine. As I said, I test the carts before shipping. 
![image](https://github.com/Polprzewodnikowy/SummerCart64/assets/21951813/e8b92371-3db1-49c7-ad1e-42e9bfa480a7)
![image](https://github.com/Polprzewodnikowy/SummerCart64/assets/21951813/533b069c-e6bb-4281-adcd-0399cca850e3)

**Comment by Polprzewodnikowy** [comment]
@Kinooshi823 are your consoles modified in any way? Like HDMI mod or an overclock?

**Comment by Kinooshi823** [comment]
> I got the cart back. Some bad news is that the hardware is fine. As I said, I test the carts before shipping. ![image](https://private-user-images.githubusercontent.com/21951813/327962258-e8b92371-3db1-49c7-ad1e-42e9bfa480a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzI3NDQsIm5iZiI6MTcxNDg3MjQ0NCwicGF0aCI6Ii8yMTk1MTgxMy8zMjc5NjIyNTgtZThiOTIzNzEtM2RiMS00OWM3LWFkMWUtNDJlOWJmYTQ4MGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAxMjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YWFmNzk2NGU5YjY0NTAwNWU0MjliZjYzNWY2N2ZiYWQ1YWM2ZDQ0NzMzNWQ5NmM0MGQ2ZThhMjk4NTBkM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BFSJYa2lEjrj_pYt2AspSniM6zn6Bqrwu4n8w64uUPc) ![image](https://private-user-images.githubusercontent.com/21951813/327962276-533b069c-e6bb-4281-adcd-0399cca850e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzI3NDQsIm5iZiI6MTcxNDg3MjQ0NCwicGF0aCI6Ii8yMTk1MTgxMy8zMjc5NjIyNzYtNTMzYjA2OWMtZTZiYi00MjgxLWFkY2QtMDM5OWNjYTg1MGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAxMjcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZGNjN2UyNzVjN2Y3ZGVjZGQxMzEwOWZmNjQ3Yzg5ZjAzYTUxZTQ0MWEzMTc3MDljZDM2ZjlkZmI4ZTM0MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mdy33dmMMDn6a2_VVYaF8dIZ2RlMtFJ4oNhdyJmFRTQ)

**Comment by Kinooshi823** [comment]
> @Kinooshi823 are your consoles modified in any way? Like HDMI mod or an overclock?

Both consoles are stock unmodded. Both have expansion paks.

**Comment by Kinooshi823** [comment]
> Contributor

Well my thing is. I paid what $120. Waited a couple months and I have issues when I get the cart.. My 64's are untouched. So for me to have a cart I paid for and not being to have it working correctly doesn't sit well with me.

**Comment by Kinooshi823** [comment]
> @Kinooshi823 are your consoles modified in any way? Like HDMI mod or an overclock?

I didn't even know you could overclock a 64

**Comment by Polprzewodnikowy** [comment]
I see you're deleting comments. Please understand that we are trying to get to the bottom of the problem, asking questions is a part of the troubleshooting. I'm still looking through the firmware code to locate any cause for this problem.

Would be great if you can update firmware and do some testing for me but preparing new firmware with more tests will take couple of days at least.

**Comment by Kinooshi823** [comment]
> I see you're deleting comments. Please understand that we are trying to get to the bottom of the problem, asking questions is a part of the troubleshooting. I'm still looking through the firmware code to locate any cause for this problem.
> 
> Would be great if you can update firmware and do some testing for me but preparing new firmware with more tests will take couple of days at least.

The comment I deleted was more of me upset of the situation and wasn't information relevant to the troubleshooting here. 

I cannot update the firmware as I don't have it in my possession and it was sent back. I am currently thinking if I want a replacement. 

Also, firmware doesn't seem to be easy right? as I am not adept with CMD.

**Comment by mariomadproductions** [comment]
> Keep in mind that custom cartridges draw more power and your power supply might just barely provide enough power to run retail game, while SC64 might get underpowered.

Is this definitely a possibility? If so, should it be documented on the readme/website?
