### ISSUE TITLE
Design a controller pak replacement

### ISSUE THREAD

**Issue by sdsnatcher73** [Polprzewodnikowy/SummerCart64#82]
I recently got my Summer Cart 64 and it is thoroughly enjoyable. But I am frustrated that saving games to controller pak is not possible. I have some old controller paks but their battery is obviously dead, I know there is this FRAM based controller pak but it’s too expensive imho. I was wondering if a Summer Cart 64 add on controller pak with no actual memory but just a USB-C port could be a feasible (and cheap) option. You could interface to a real controller just like the original controller pak but have the Summer Cart 64 handle all the actual storage (like it does for games with cart based saves). An alternative would be a USB-C to joypad port cable, so you could plug that into one of the unused ports of the N64 (I suppose this would require some more work but I don’t know the details of how the controller pak is spoken to by the software.

I don’t know if the USB-C port is even usable in such a way either.

**Comment by networkfusion** [comment]
This is not possible due to the N64 design!

**Comment by Polprzewodnikowy** [comment]
![Screenshot_20240804_184708](https://github.com/user-attachments/assets/7cf24b52-512a-485e-a204-fe027185f67d)
