### ISSUE TITLE
Consider adding an option for 240p in menu

### ISSUE THREAD

**Issue by manticStack** [Polprzewodnikowy/SummerCart64#89]
Some ntsc consoles that have been transcoded to pal-m appears to be an flashing image bug when showing an image in 480i, adding an option for 240p should help

**Comment by Polprzewodnikowy** [comment]
Wrong place to report such issue. This repo doesn't contain the menu code and the same exact issue is reported here https://github.com/Polprzewodnikowy/N64FlashcartMenu/issues/82
