### ISSUE TITLE
[SC64][BUG] Bad CPU type in executable

### ISSUE THREAD

**Issue by BenoitCaron** [Polprzewodnikowy/SummerCart64#95]
### Is your issue really a bug?

- [X] My issue is indeed a bug in the flashcart firmware and/or documentation and I can prove it.
- [X] I understand the difference in responsibilities between flashcart firmware and menu software.

### Firmware version

v2.20.0

### Describe the bug

I'm trying to update the firmware with my Intel Mac. It appears the sc64deployer executable is only built for ARM Macs. Would it be possible to compile it for Intel Macs as well?

### Output logs from `sc64deployer info`

```shell
-bash: ./sc64deployer: Bad CPU type in executable
```

**Comment by Polprzewodnikowy** [comment]
I don't consider this a bug. This is a solo developer project and I don't have time to support legacy systems - configuring cargo to produce fat macOS binary is not trivial and I'm not willing to spend the time to develop and test such build.

In the meantime you can compile the application yourself - source is available. Feel free to submit a PR to the CI/CD build process if you could figure this out.

**Comment by iambmelt** [comment]
Here’s what worked for me to build sc64deployer on an Intel Mac:

```sh
xcode-select -p >/dev/null 2>&1 || xcode-select --install
brew install llvm pkg-config autoconf automake libtool
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source "$HOME/.cargo/env"
```

Then build with

```sh
cd sw/deployer
export LIBCLANG_PATH="$(brew --prefix llvm)/lib"
cargo build --release
```

The binary ends up at `target/release/sc64deployer`. The critical bit is setting `LIBCLANG_PATH`; without it, `bindgen` fails.

**Comment by SasinHyeonmu** [comment]
### Building Your Native Architecture Only

@iambmelt Interesting enough, I didn't have to do anything with `LIBCLANG_PATH` myself and that's not defined in my setup. I just had to install the Rust toolchain and Cargo using the instructions [here](https://doc.rust-lang.org/cargo/getting-started/installation.html) (though I already have Xcode set up as a developer and may be getting benefits from the whole host of things I have installed via Homebrew). Here were my steps in bash:

```
cd sw/deployer                            # Go to where the sc64deployer app is
curl https://sh.rustup.rs -sSf | sh       # Install Rust/cargo
. "$HOME/.cargo/env"                      # For bash & zsh used this to configure current shell
cargo -h                                  # Confirm install is good and print the help. If you don't see it, restart your shell & ensure PATH includes $HOME/.cargo/bin
cargo check
cargo build                               # Note, I did build for debug for myself rather than release flavor 
```

### Building Universal Binary

On making Universal builds for macOS, it seems [cargo-universal2](https://crates.io/crates/universal2) works for that purpose. Here's the steps I did to build it the Universal fat binary (assuming you've already installed Cargo/Rust, have Xcode properly installed, etc.)

1. Run `cargo install universal2@0.0.1`. There is a newer version, but I experienced errors building with that one as it seems like the "universal2" argument was getting passed to `cargo build` erroneously and it subsequently barfed and exited. v0.0.1 doesn't have these issues, but lacks the ability to add the other arguments may want for `cargo build` and so universal2 will only build release builds.
2. Ensure you have both architectures available in the Rust toolchain or your build will fail. They can be added using these commands:
```
rustup target add x86_64-apple-darwin
rustup target add aarch64-apple-darwin
```
3. Run `cargo universal2`
4. The Universal binary is going to be created at `./target/universal2-apple-darwin/release/sc64deployer`. Copy that to wherever you want the binary.

Was able to confirm locally on my Intel iMac and my Apple Silicon M1 Mac Mini that this creates a working binary for both platforms.

@Polprzewodnikowy I have little experience with Rust, but will give a shot at creating a PR to the CI/CD build process in the next week. Would be curious your thoughts on if integrating in cargo-universal2 makes sense or if you'd prefer the CI/CD modified to incorporate what it's doing manually (building each architecture and then lipo'ing it) to minimize dependencies in build process.

**Comment by SasinHyeonmu** [comment]
For folks who arrive here, unofficial Intel Mac support via Universal binary can be found on my fork [here](https://github.com/SasinHyeonmu/SummerCart64/releases/tag/v2.20.3). Use at your own risk until PR #120 gets merged into the official project. If you experience issues with the builds on my fork, please raise them over in my [fork repo](https://github.com/SasinHyeonmu/SummerCart64) and not in this repo's issues.
