### ISSUE TITLE
[SC64][BUG] 

### ISSUE THREAD

**Issue by Mario1981** [Polprzewodnikowy/SummerCart64#98]
### Is your issue really a bug?

- [X] I understand the difference between flashcart firmware, N64FlashcartMenu and `sc64deployer` PC app.
- [ ] I found a bug in FPGA HDL (`/fw/rtl`)
- [ ] I found a bug in MCU app (`/sw/controller`)
- [ ] I found a bug in N64 bootloader (`/sw/bootloader`)
- [ ] I found a bug in PC app (`/sw/deployer`)
- [ ] I found a bug in initial programming script (`/sw/tools/primer.py`)
- [ ] I found an error in documentation (`/docs`)
- [X] I found an issue elsewhere

### Firmware version

v2.20.2

### Describe the bug

I updated my SC64. Everything is fine. But I still have the same issue as before. Loading US/JAP/DD Games I have no sound on my european N64. On european games sound works. Is this suppose to behave this way ?
Best regards

**Comment by Polprzewodnikowy** [comment]
This is not a SC64 bug. It's a problem with your AV equipment. Running games from other regions isn't as straightforward as it seems at a first glance. Please test these games with different TV / upscaler / capture card or anything else in your AV path that goes between the console and the other end. It's hard to tell which of those are the issue as you haven't provided any information about your setup.
